### ISSUE TITLE
Height over 768 bug

### ISSUE THREAD

**Issue by Qwiko** [llorentegerman/react-admin-dashboard#8]
When the heigth of the screen is over 768 and width lower than 768 something weird happens when clicking outside the expanded sidebar.

**Comment by llorentegerman** [comment]
Hi! thanks for your comment.
It's really weird, I'm not sure, but I think it's related to Chrome, I haven't been able to reproduce this error on Safari.
As you said, the problem happens when you are in a screen with sizes: `width < 768` and `height > 768`, for example: 600px x 800px.
When the Sidebar is expanded and you click outside, for a moment window.innerWidth is 800px, I'm not sure why, but you can check it out using a `console.log(window.innerWidth)` in the render method.
Anyway, I have fixed it rewriting the **SidebarComponent** to use React Hooks, and forcing a re-render after each change of `window.innerWidth`.
You can check it out in PR #9 
I hope that was helpful
